### ISSUE TITLE
How to define a callback to the ngrok-go/1.1.0 agent to implement dashboard STOP

### ISSUE THREAD

**Issue by abakum** [ngrok/ngrok-go#102]
For ngrok-go/1.1.0 I try STOP agent from dashboard.ngrok.com then got:
>ERR_NGROK_805 This ngrok agent does not support remote stopping: the agent has not defined a callback for this operation.
How to define a callback for this operation?

**Comment by inconshreveable** [comment]
you want to use `WithStopHandler` https://pkg.go.dev/golang.ngrok.com/ngrok#WithStopHandler

e.g.

```
ngrok.Listen(
   ngrok.WithAuthtokenFromEnv(),
   ngrok.WithStopHandler(func(ctx context.Context, sess ngrok.Session) error {
      go func() { sess.Close() }()
      return nil
   }
)
```

**Comment by abakum** [comment]
Thanks! It works.
How to eliminate:
>ERR_NGROK_810
There was a networking error while trying to send this operation to the ngrok agent or trying to read the response. This usually indicates that the ngrok agent was in the process of shutting down or reconnecting, but it could also result from a networking timeout or failure. It is possible, but unlikely, that the operation succeeded.

**Comment by inconshreveable** [comment]
you may need to sleep in the goroutine before calling sess.Close() to give the library time to send the successful response  to the STOP command back to the server. it's clumsy, i know

**Comment by abakum** [comment]
```
ct, ca := context.WithCancel(ctx)
	tun, err := ngrok.Listen(ct,
		config.TCPEndpoint(),
		ngrok.WithAuthtoken(Getenv("NGROK_AUTHTOKEN", NGROK_AUTHTOKEN)),
		ngrok.WithStopHandler(func(ctx context.Context, sess ngrok.Session) error {
			go func() {
				time.Sleep(time.Millisecond * 10)
				ca()
				// sess.Close()
			}()
			return nil
		}),
	)
```
