### ISSUE TITLE
How to skip warning screen 

### ISSUE THREAD

**Issue by Izumra** [ngrok/ngrok-go#121]
ngrok http 8080 --host-header=rewrite --request-header-add "ngrok-skip-browser-warning: t;"

Command doesn't work and i still refer to the warning ngrok page. How i can that fix. I need set this header from client side but websocket conn doesn't provide addition parameters for configure headers. How i can skip warning page and directly reference to the route

**Comment by russorat** [comment]
@Izumra thank you for this issue! i'm looking into how we can remove the abuse interstitial for websocket requests. If you want to follow up, send a note to russ@ngrok.com, i'll let you know what we find out.
