### ISSUE TITLE
the fmt and generate diff checks don't actually verify anything

### ISSUE THREAD

**Issue by jrobsonchase** [ngrok/ngrok-go#57]
Either the fmt/generate steps aren't modifying files, the changes are getting reverted before the `git diff --exit-code` step runs, or `git diff` isn't operating on what we think it's operating on. Regardless, these CI tests do nothing currently.

**Comment by euank** [comment]
```
Run make -f scripts/Makefile gen-proto && git status
protoc --go_out=. --go_opt=module=golang.ngrok.com/ngrok ./internal/pb/middleware.proto
HEAD detached at pull/1/merge
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	golang.ngrok.com/

nothing added to commit but untracked files present (use "git add" to track)
```

Looks like the module thing is not detecting the module we're in correctly.
