### ISSUE TITLE
How to use specic port with this

### ISSUE THREAD

**Issue by kateile** [ngrok/ngrok-go#66]
I was using `ngrok http 7373` from bash now I want to switch to this but I can't figure how.

This is how I use it 
```go
tun, err := ngrok.Listen(context.Background(),
			config.HTTPEndpoint(),
			ngrok.WithAuthtokenFromEnv(),
		)
		if err != nil {
			log.Printf("ngrok error: %s", err.Error())
			return
		}

		log.Println("tunnel created:", baseUrl)
```

**Comment by russorat** [comment]
Hi @kateile, This library is intended to be embedded directly into the go application you are running on port 7373, such that the requests are sent directly to your handler function. 

Can you explain a little more about the reason you'd like to send traffic to another port using this library?

**Comment by kateile** [comment]
@russorat thanks for response.

Running ngrok via bash seems to work fine. But with this lib I get [ERR_NGROK_3004](https://ngrok.com/docs/errors/err_ngrok_3004). That's why I thought may be I might be missing something on port configuration.

I will try to reproduce on it another repository.

**Comment by jrobsonchase** [comment]
Hey @kateile!

We're working on adding built-in connection forwarding to the library to support this kind of usecase out of the box. You can find the draft of it here: #74.

If this is still something you're trying to do, we'd love some feedback!

**Comment by NotSoSeriouss** [comment]
Can you provide a minimal explanation on how to achieve this while the new version is getting released?

**Comment by jrobsonchase** [comment]
This was actually released a few months ago! You want either the top-level [ListenAndForward](https://pkg.go.dev/golang.ngrok.com/ngrok#ListenAndForward) function, or the `ListenAndForward` method on the [Session](https://pkg.go.dev/golang.ngrok.com/ngrok#Session) interface. A minimal example can be found [here](https://github.com/ngrok/ngrok-go/blob/main/examples/ngrok-forward-lite/main.go).
