### ISSUE TITLE
Not clear in documentation how to achieve the same functionality of `ngrok tls --terminate-at edge`

### ISSUE THREAD

**Issue by ucirello** [ngrok/ngrok-go#86]
I am working on integrating ngrok in an internal workflow here. Because of particularities of the protocol used, I need it to use with TLS terminating the encryption at the edge aka `ngrok tls --terminate-at edge`.

The Go SDK doesn't document how to achieve that and it seems to default to some other mode.

Appreciate the difference between these two setups:
```
	tun, err := ngrok.Listen(ctx,
		config.TLSEndpoint(
			config.WithDomain(ngrokDomain),
			config.WithTermination([]byte{}, []byte{}),
		),
		ngrok.WithAuthtokenFromEnv(),
	)
```

vs

```
	tun, err := ngrok.Listen(ctx,
		config.TLSEndpoint(
			config.WithDomain(ngrokDomain),
		),
		ngrok.WithAuthtokenFromEnv(),
	)
```

**Comment by jrobsonchase** [comment]
Huh, I was actually unaware of that behavior! Agreed that it warrants documentation and maybe a dedicated method of its own. Seems like an awkward API to have to pass empty slices to get the desired result.

**Comment by ucirello** [comment]
@jrobsonchase I open a PR as a suggestion. In any case, please, feel free to close it and do it under your own licensing terms. Thanks!

**Comment by russorat** [comment]
@ucirello what are your thoughts on #88 ? Do the function names make sense to you and your mental model?

**Comment by ucirello** [comment]
@russorat I think the suggested terms are good in my opinion.
